language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  - 'MY_APP_NAME=OREORE-WAF-2017-Spring MY_APP_ENV=dev MY_APP_DEFAULT_LOG_LEVEL=DEBUG MY_APP_DB_DSN=sqlite::memory: MY_APP_DB_USERNAME=test MY_APP_DB_PASSWORD=test'

install:
  - composer install --no-interaction

script:
  - vendor/bin/codecept run functional
  - vendor/bin/codecept run unit
